name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.1
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download
    
    - name: Test
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test --define version="" //apps/...

    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      if: ${{ github.ref == 'refs/heads/develop'}}
      run: |
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u squzy --password-stdin
        wget https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel-1.1.0-installer-linux-x86_64.sh -O bazel_installer.sh
        chmod +x bazel_installer.sh
        ./bazel_installer.sh --user
        export PATH="$PATH:$HOME/bin"
        bazel --version
        export SQUZY_VERSION=latest
        bazel run --stamp --workspace_status_command=./scripts/status.sh --define version=latest //apps/squzy_monitoring:squzy_push_hub_ci